-- ============================================================================
-- Migration 20: a much richer news library
--
-- The tick spawns news by picking a weighted-random event_template, targeting
-- a random asset/sector, and rolling a randomized impact within the template's
-- range. More templates = far more variety in the feed. Idempotent by code.
-- ============================================================================

insert into public.event_templates
  (code, scope, headline_template, body_template,
   fv_impact_min, fv_impact_max, vol_multiplier, duration_seconds, weight, class_id) values

  -- ---- Stock: company-specific ------------------------------------------
  ('buyback',        'asset', '{name} announces a huge share buyback',
   '{symbol} will return billions to shareholders. The market reads it as confidence.',
   0.03, 0.09, 1.3, 800, 2, 'stocks'),
  ('dividend_hike',  'asset', '{name} raises its dividend',
   'Income investors cheer as {symbol} lifts its payout for the tenth year running.',
   0.02, 0.05, 1.1, 600, 2, 'stocks'),
  ('guidance_raise', 'asset', '{name} raises full-year guidance',
   'Management now expects a much stronger year. {symbol} targets get marked up.',
   0.04, 0.10, 1.5, 900, 2, 'stocks'),
  ('guidance_cut',   'asset', '{name} slashes its outlook',
   '{symbol} warned that the rest of the year looks tougher than hoped.',
   -0.11, -0.04, 1.7, 900, 2, 'stocks'),
  ('ceo_out',        'asset', '{name} CEO steps down abruptly',
   'The sudden exit at {symbol} leaves investors guessing about what went wrong.',
   -0.10, -0.02, 1.9, 1000, 1, 'stocks'),
  ('star_hire',      'asset', '{name} poaches a superstar CEO',
   'A legendary operator is taking the helm at {symbol}. Expectations soar.',
   0.03, 0.09, 1.5, 800, 1, 'stocks'),
  ('merger',         'asset', '{name} is in merger talks',
   'Reports say {symbol} is exploring a blockbuster combination. Bankers circle.',
   0.05, 0.14, 2.0, 1100, 1, 'stocks'),
  ('buyout_rumor',   'asset', 'Takeover rumor swirls around {name}',
   'Traders are betting a suitor wants {symbol} at a fat premium.',
   0.04, 0.12, 1.9, 900, 1, 'stocks'),
  ('lawsuit',        'asset', '{name} hit with a major lawsuit',
   'A costly legal fight lands on {symbol}. Investors brace for damages.',
   -0.09, -0.03, 1.6, 1000, 1.5, 'stocks'),
  ('recall',         'asset', '{name} announces a sweeping recall',
   '{symbol} is pulling products from shelves. The bill won''t be small.',
   -0.08, -0.03, 1.6, 900, 1.5, 'stocks'),
  ('short_report',   'asset', 'Short-seller takes aim at {name}',
   'A scathing report accuses {symbol} of cooking the books. Shares wobble.',
   -0.16, -0.06, 2.3, 1200, 1, 'stocks'),
  ('viral_moment',   'asset', '{name} goes viral',
   'A meme, a moment, a stampede of retail traders — {symbol} is the talk of the feed.',
   0.05, 0.15, 2.2, 700, 1, 'stocks'),
  ('layoffs',        'asset', '{name} announces deep layoffs',
   '{symbol} is cutting staff to protect margins. Cost-cutting cheers, growth fears.',
   -0.05, 0.03, 1.5, 800, 1.5, 'stocks'),
  ('breakthrough',   'asset', '{name} unveils a breakthrough',
   'A genuine technical leap at {symbol} has competitors scrambling.',
   0.05, 0.13, 1.8, 900, 1.5, 'stocks'),
  ('partnership',    'asset', '{name} lands a landmark partnership',
   'A marquee deal gives {symbol} a huge new distribution channel.',
   0.03, 0.08, 1.3, 700, 2, 'stocks'),
  ('data_breach',    'asset', '{name} suffers a data breach',
   'Millions of records exposed at {symbol}. Trust — and the stock — takes a hit.',
   -0.09, -0.03, 1.7, 1000, 1, 'stocks'),
  ('insider_buy',    'asset', '{name} insiders are buying',
   'Executives at {symbol} are putting their own money in. A bullish tell.',
   0.02, 0.06, 1.2, 600, 2, 'stocks'),

  -- ---- Sector-wide -------------------------------------------------------
  ('supply_shock',   'sector', 'Supply crunch slams the {sector} sector',
   'Shortages ripple through {sector} names. Costs up, output down.',
   -0.08, -0.03, 1.6, 1100, 1.5, null),
  ('sector_tailwind','sector', '{sector} rides a demand wave',
   'A surge of orders lifts the whole {sector} sector.',
   0.03, 0.09, 1.4, 1000, 2, null),
  ('strike',         'sector', 'Workers strike across {sector}',
   'A walkout halts production in the {sector} sector.',
   -0.07, -0.02, 1.5, 1000, 1, null),
  ('subsidy',        'sector', 'Government unveils {sector} subsidies',
   'Fresh public money flows into {sector}. Investors pile in.',
   0.03, 0.10, 1.5, 1100, 1, null),
  ('breakthrough_sec','sector','Innovation wave sweeps {sector}',
   'A new technology promises to reshape the {sector} sector.',
   0.02, 0.07, 1.4, 900, 1.5, null),

  -- ---- Macro / market ----------------------------------------------------
  ('inflation_hot',  'market', 'Inflation runs hotter than expected',
   'Sticky prices stoke fears of tighter policy. Risk assets sell off.',
   -0.06, -0.02, 1.5, 1300, 1, null),
  ('inflation_cool', 'market', 'Inflation cools, relief rally ensues',
   'Softer prices raise hopes of easier policy. Buyers step in everywhere.',
   0.02, 0.06, 1.3, 1300, 1, null),
  ('jobs_strong',    'market', 'Blockbuster jobs report',
   'The economy is humming. Good news for earnings, mixed news for rates.',
   0.01, 0.05, 1.2, 1200, 1, null),
  ('recession_fear', 'market', 'Recession fears grip markets',
   'Gloomy data has traders bracing for a downturn. Everything dips.',
   -0.08, -0.03, 1.8, 1500, 0.8, null),
  ('geopolitical',   'market', 'Geopolitical shock rattles markets',
   'Headlines from abroad send a jolt of risk-off through every sector.',
   -0.07, -0.02, 1.9, 1400, 0.8, null),
  ('stimulus',       'market', 'Surprise stimulus package announced',
   'A wave of fresh spending lifts sentiment across the board.',
   0.02, 0.07, 1.4, 1300, 1, null),
  ('santa_rally',    'market', 'Animal spirits take over',
   'Pure momentum. Everyone''s buying because everyone''s buying.',
   0.02, 0.06, 1.5, 900, 0.8, null),

  -- ---- Crypto ------------------------------------------------------------
  ('crypto_etf',     'asset', 'Spot ETF approved for {name}',
   'Wall Street can finally buy {symbol} in a wrapper. The floodgates open.',
   0.10, 0.28, 2.2, 1000, 1.2, 'crypto'),
  ('crypto_hack',    'asset', 'Exchange hack hits {name}',
   'A major exchange was drained. Holders of {symbol} scramble for the exits.',
   -0.28, -0.10, 2.6, 1100, 1.2, 'crypto'),
  ('crypto_endorse', 'asset', 'Billionaire tweets about {name}',
   'One post, one rocket emoji, and {symbol} is off to the races.',
   0.06, 0.22, 2.4, 700, 1.2, 'crypto'),
  ('crypto_ban',     'asset', 'Country moves to ban {name}',
   'A major economy signals a crackdown. {symbol} plunges on the news.',
   -0.22, -0.08, 2.4, 1100, 1, 'crypto'),
  ('crypto_upgrade', 'asset', '{name} ships a major network upgrade',
   'Faster, cheaper, greener — the {symbol} upgrade goes live without a hitch.',
   0.05, 0.16, 1.9, 900, 1.2, 'crypto'),

  -- ---- Real estate -------------------------------------------------------
  ('rate_relief_re', 'sector', 'Falling rates lift {sector} property',
   'Cheaper mortgages breathe life into {sector} real estate.',
   0.03, 0.08, 1.3, 1200, 1, 'real_estate'),
  ('vacancy_spike',  'asset', 'Vacancies climb at {name}',
   'Empty units are eating into {symbol}''s rental income.',
   -0.08, -0.03, 1.5, 1200, 1, 'real_estate'),
  ('occupancy_boom', 'asset', '{name} hits record occupancy',
   'Every unit is full and rents are rising. {symbol} landlords are grinning.',
   0.03, 0.07, 1.2, 1100, 1, 'real_estate'),

  -- ---- Forex -------------------------------------------------------------
  ('cb_hawkish',     'asset', 'Central bank turns hawkish on {name}',
   'Rate-hike signals ripple through {symbol}.',
   -0.03, 0.03, 1.5, 1100, 1, 'forex'),
  ('trade_data',     'asset', 'Trade data jolts {name}',
   'A surprise in the numbers sends {symbol} swinging.',
   -0.025, 0.025, 1.4, 1000, 1, 'forex'),
  ('intervention',   'asset', 'Central bank intervenes to defend {name}',
   'Officials step into the market. {symbol} whipsaws.',
   -0.03, 0.03, 1.8, 1200, 0.8, 'forex')

on conflict (code) do nothing;
